# Generated by Django 4.2.1 on 2023-07-12 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fridge name')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date in the system')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Details about the fridge')),
                ('owners', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Recipe title')),
                ('image_link', models.CharField(max_length=300, verbose_name='Link to image')),
                ('link', models.CharField(max_length=300, verbose_name='Link to recipe')),
                ('api_likes', models.IntegerField(null=True, verbose_name='Likes by API users')),
                ('if_saved', models.BooleanField(default=False)),
                ('saved_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('expire_date', models.DateTimeField(verbose_name='Expiration date of the product')),
                ('amount', models.FloatField(verbose_name='Amount of the product stored')),
                ('amount_unit', models.CharField(choices=[('Pieces', 'Pieces'), ('Grams', 'Grams'), ('Kilograms', 'Kilograms'), ('Carton', 'Carton'), ('Bottle', 'Bottle'), ('Jar', 'Jar'), ('Can', 'Can'), ('Package', 'Package'), ('Container', 'Container')], default='Grams', max_length=32)),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Details about the ingredient')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date in the system')),
                ('fridge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge.fridge')),
            ],
        ),
    ]
