# Generated by Django 4.2.2 on 2023-06-21 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fridge name')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date in the system')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Details about the fridge')),
            ],
        ),
        migrations.CreateModel(
            name='FridgeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, verbose_name='User email')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date in the system')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('expire_date', models.DateTimeField(verbose_name='Expiration date of the product')),
                ('amount', models.FloatField(verbose_name='Amount of the product stored')),
                ('amount_unit', models.CharField(choices=[('Pieces', 'Pieces'), ('Grams', 'Grams'), ('Kilograms', 'Kilograms'), ('Carton', 'Carton'), ('Bottle', 'Bottle'), ('Jar', 'Jar'), ('Can', 'Can'), ('Package', 'Package'), ('Container', 'Container')], default='Grams', max_length=32)),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Details about the ingredient')),
                ('fridge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge.fridge')),
            ],
        ),
        migrations.AddField(
            model_name='fridge',
            name='owners',
            field=models.ManyToManyField(blank=True, to='fridge.fridgeuser'),
        ),
    ]
