name: Django CI

on:
  push:
    branches: [ "tests", "deployment" ]
  pull_request:
    branches: [ "tests", "deployment" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, '3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Fridge Tests
      run: python fridgemanager/manage.py test fridge.tests
    - name: Run Members Tests
      run: python fridgemanager/manage.py test members.tests